version: '3.1'
services:
  app:
    image: 'hello-world:latest'
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 64M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        max_attempts: 10
networks:
  frontend:
    external: true
