version: "3.1"
services:
  app2:
    image: hello-world
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 64M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        max_attempts: 10
      labels:
        traefik.backend.loadbalancer.swarm: "false"
        traefik.frontend.rule: "Host:hello.garamundo.pro"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.entryPoints: "http"
        traefik.port: "80"
        traefik.docker.network: "frontend"

networks:
  frontend:
    external: true
